### PR TITLE
Issue3

### PR DESCRIPTION
**Pull request by OlegAndreych**

### CODE REVIEW

**Comment by maltalex** [comment]
Hi Oleg

Sorry it took a while. I've been busy, then on vacation, then busy again :)

Anyway, I've reviewed the code and made some changes. The commits are pretty atomic, so they should be pretty straightforward to look over. I'd appreciate it if you could take a look, make sure I haven't made a mistake or missed anything before the change is merged into master.

**Comment by OlegAndreych** [comment]
I'm not that good at writing library code, so I just want to know about making helper methods protected. My thought was that a user in need to extend IPRange would just override `merge` and `extend` methods altogether implementing their own helper functions suited for their own needs with delegating to super in a fallback situation.
 Other than that everything seems like unquestionably great additions to the code.

**Comment by maltalex** [comment]
I personally try to avoid using `private` methods to allow responsible adults to use whatever they find useful without resorting to dirty tricks which we've all had to perform ourselves at some point to get to something useful that's been hidden from us. That's why I default to `package-private` or `protected` unless there's an obvious reason to set something to `private`.

**Comment by maltalex** [comment]
I've decided you're right, these are trivial helper methods internal to `IPRange`. There's no reason for `ineter` users to depend on them, especially when they are very easy to implement.

**Pull request merged**
