### PR TITLE
fix #1 Should it be allowed to create range from single address?

### LINKED ISSUE #1: Should it be allowed to create range from single address?
I think it should be allowed to create an IPv4Range and IPv6Range from a single address like:
```java
IPv6Range.of("1::")
IPv4Range.between("127.0.0.1")
```
I want it to be allowed because sometimes single address is a special case of a range and it's convenient to have uniform processing of all the data you have.

### PR DESCRIPTION
**Pull request by OlegAndreych**

### CODE REVIEW

**Comment by maltalex** [comment]
Thanks, Oleg, this is a very nice contribution.

A few notes:

1. I don't see a lot of point in having a separate `Parsers` class.  
Both IPv4Address and IPv6Address already share a base class, the parsing methods could go there as private methods. Although I do have plans to replace the abstract ineter classes with interfaces later on for the sake of simplicity, and private methods in interfaces are only available in Java 9+...
Also, the functional approach is elegant, but you have to remember that it's not likely we'll need to implement IPv7 or IPv8 anytime soon, so there's no real need to generify the code - simple is better here in my opinion. Even if it comes at the cost of similar code in two different classes. 

2. You're absolutely right that we should unify the mask type to `int`. I'm not sure why I chose `byte` at the time.

3.  The exception in the range parsing function should be avoided. Exceptions aren't cheap to create (they capture the stack trace on creation), and parsing a huge number of IPs/Ranges/Subnets in a loop is a conceivable use of ineter.
It's possible to just check the last few chars of the String before trying to parse the String as a subnet.  The slash can only be in two different locations for IPv4 (the location before last - `1.0.0.0/1` , and the one before that - `1.0.0.0/22`). We don't even need a loop, just check `length()-2` and `length()-3`. For IPv6 we would need a loop due to the Zone ID.

If you'd like, you can make some changes yourself, or I can merge the code as-is and continue working on it myself.

**Comment by OlegAndreych** [comment]
1. It's a good point that there's an abstract class for `IPvXRange`, so it will be a good fit to place common parsing methods. As you consider, that there's not much duplication for parsing methods, I see a little to none additional complexity in making solution generic. 
At this point, there's not much to discuss, so I'll accept any decision you'll make. So should we use distinct implementations of parse methods, or just move generic parsing methods to abstract parent and resort to simple inheritance instead of functional machinery?

2. OK, but I'll leave it for future contributions if you don't mind.

3. I absolutely agree about exceptions and analysis of a couple of last characters is a nice first step to me. Should we consider to add validation methods for addresses, ranges, and subnets, so that user can check whether something is a valid address-thingy and avoid exceptions altogether? I also propose a JMH test to check will double validation (on validation itself and construction) would be cheaper than exception handling, so we can decide on future steps later.

So what do you think?
If you're not in a hurry I can add fixes for this PR by myself.

**Comment by OlegAndreych** [comment]
While waiting for an answer I've created an example, where common parsing methods are moving to abstract IPRange class.

**Comment by maltalex** [comment]
1. The combined parsing in IPRange looks fine. Let's keep it as-is. I just added a missing "protected" keyword and some javadoc.

2. Yeah, the mask size is a separate issue. It's also (slightly) breaking so we'll do it later.

3. Yes, methods for checking whether a String is a valid address, range or subnet are a good idea. I had a few of those at some point in the past, but at some point I left just the exception-throwing builders. Would you like to add them? This can be a separate PR. I'm not in any hurry, I'm just making sure you're comfortable with the slight scope creep we seem to be having :)

**Comment by OlegAndreych** [comment]
As far as we agree that parsing in IPRange is fine, I think validation methods can be done as a separate issue.
If there are no other issues with this PR, I think we can merge it and move on to the new great ones. )

**Pull request merged**
